// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkxhaedaekxosbyzmjit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtreGhhZWRhZWt4b3NieXptaml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTY2MTEsImV4cCI6MjA2NTI5MjYxMX0.zwPlGGB-_lODoO_SbubdZezWFTrBGAcGi6BiFFydG28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);